language: node_js
node_js:
  - lts/dubnium
  - node
sudo: false
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: Pjl0kiAPE3E6qA1EYFrGj9oKUehJpANttmVTcZAUT8s0M24Nxro9uwVErVpPTCeQZc5XUvXr47hU4w3HDFbICW4QJ++TKuXtMvgW7Cy7aLSYzltm5Ukl8M/8CqATSU66mo58/Q0kWrNNH/zr+a4CvWTYuiYOxtVsBXUfIiksd68=
  file:
    - 'profanities.js'
    - 'profanities.min.js'
  on:
    tags: true
